name: Pull Request

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths-ignore:
      - 'docs/**'

env:
  BASE_BRANCH: 'main'

jobs:
  check-changesets:
    name: Check changesets
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check for changes in .changeset directory
      id: check-changesets
      run: |
        git fetch origin $BASE_BRANCH

        if git diff --name-only origin/main HEAD -- .changeset | grep -q '\.md$'; then
          echo "✅ Changes in .changeset directory"
        else
          echo "❌ No Changes in .changeset directory"
          exit 1
        fi
